apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: emoji-svc.emojivoto.svc.cluster.local
  namespace: emojivoto
spec:
  retryBudget:
    retryRatio: 0.001
    minRetriesPerSecond: 10
    ttl: 10s
  routes:
  - condition:
      method: POST
      pathRegex: /emojivoto\.v1\.EmojiService/ListAll
    name: ListAll
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /emojivoto\.v1\.EmojiService/FindByShortcode
    name: FindByShortcode
    isRetryable: true
